cat_w_sites = [
    # 0
    ('Adult', {
        "http://ryogamasaki.netfirms.com/",
        "http://members.tripod.com/~chaz16/3.html",
        "http://www.hentai-comics.com/",
        "http://www.jastusa.com/",
        "http://www.peachprincess.com/",
        "http://www.g-collections.com",
        "http://www.hentai-games.com/",
        "http://www.canadahentai.com",
        "http://www.hirameki-int.com",
        "http://www.himeyashop.com/",
    }),
    # 1
    ('Arts', {
        "http://www.auburn.edu/student_info/anime_manga/",
        "http://www.freewebs.com/shanimeclub/",
        "http://www.indyanime.org",
        "http://www.fresnoanime.com",
        "http://www.otakuanime.org",
        "http://www.delawareanimesociety.com",
        "http://www.ctrl-a.org",
        "http://www.sfanimeclub.com/",
        "http://www.stevens.edu/anime/",
        "http://www.jaamke.com/",
    }),
    # 2
    ('Business', {
        "http://www.aicpa.org/",
        "http://www.cica.ca/",
        "http://www.isaca.org/",
        "http://www.accountants.org.sg/",
        "http://www.icaa.org.au/",
        "http://www.icai.ie/",
        "http://www.icap.org.pk/",
        "http://www.jicpa.or.jp/index.html",
        "http://www.nasba.org/",
        "http://www.cma-canada.org/",
    }),
    # 3
    ('Computers', {
        "http://www.cs.ucr.edu/~stelo/pattern.html",
        "http://www.oopweb.com/algorithms/files/algorithms.html",
        "http://www.intelligenceunited.com/index2.html",
        "http://www.leekillough.com/heaps/",
        "http://sigact.acm.org/",
        "http://www.personal.kent.edu/~rmuhamma/algorithms/algorithm.html",
        "http://www.eli.sdsu.edu/courses/fall95/cs660/notes/",
        "http://www.algosort.com/",
        "http://alumni.imsa.edu/~matth/quant/299/paper/",
        "http://editor.altervista.org/",
    }),
    # 4
    ('Games', {
        "http://www.5straight.com/",
        "http://www.gamereport.com/tgr20/5ivestraight.html",
        "http://www.gamerz.net/pbmserv/amazons.html",
        "http://ourworld.compuserve.com/homepages/dennis_matheson/3m21.htm",
        "http://www.boardgamegeek.com/game/2545",
        "http://www.enginuity.com/dwild.htm",
        "647323,http://www.renju.net/,Games",
        "http://www.linkfive.com/linkfivethegame.html",
        "http://www.oellermann.com/morabaraba",
        "http://www.cox-tv.com/games/rules/morris.html",
    }),
    # 5
    ('News', {
        "http://news.bbc.co.uk/",
        "http://abcnews.go.com/",
        "http://www.nytimes.com/",
        "http://www.cnn.com/",
        "http://www.cbsnews.com/",
        "http://www.newsinpictures.com/",
        "http://www.cbc.ca/news/",
        "http://www.guardian.co.uk/",
        "http://english.aljazeera.net/",
        "http://www.foxnews.com/",
    }),
    # 6
    ('Recreation', {
        "http://www.ukulele.com/",
        "http://www.antiquelures.com/",
        "http://www.currierprints.com",
        "http://www.debencemusicworld.com",
        "http://antiquerestorers.com/",
        "http://www.tefaf.com",
        "http://www.colonialarts.com/retablos.htm",
        "http://www.charleslocksmith.com",
        "http://www.restoration-advice.org/",
        "http://www.bassboy.com.au/getreel/",
    }),
    # 7
    ('Science', {
        "http://www.usda.gov/",
        "http://www.fao.org/ag",
        "http://www.ruaf.org/",
        "http://www.niab.com/",
        "http://www.agr.gc.ca/",
        "http://dels.nas.edu/banr/",
        "http://www.farminfo.org/",
        "http://www.ciat.cgiar.org",
        "http://www.infosysplus.org/",
        "http://www.garden-infosys.de/",
    }),
    # 8
    ('Shopping', {
        "http://tias.com/stores/grannyscupboard",
        "http://www.go-kat-go.com/",
        "http://monimania.home.att.net",
        "http://www.decodan.com",
        "http://www.decoworld.com",
        "http://www.ohioseeburgrepair.com",
        "http://www.dowahdiddy.com/",
        "http://www.trashdaddy.com/",
        "http://ourworld.cs.com/sllmt12345",
        "http://www.classicmalt.com",
    }),
    # 9
    ('Sports', {
        "http://www.oarevents.com/",
        "http://www.hairyscaryevolutions.com/",
        "http://www.checkpointzero.com",
        "http://www.active.com/moresports/adventureracing/",
        "http://www.archronicles.com/",
        "http://www.ar.co.za",
        "http://www.fmij.com",
        "http://www.dynamicadventureracing.co.uk/",
        "http://www.infiterrasports.com",
        "http://www.indianaar.com/",
    }),
]